services:
  - type: web
    name: appreader-tts-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tts-server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true

